dist: xenial
language: cpp
compiler: clang
addons:
  apt:
    sources:
    - llvm-toolchain-xenial-7
    packages:
    - libc++-7-dev
    - libc++abi-7-dev
    update: true
install:
- sudo pip install conan
script:
- sudo conan install -s compiler=clang -s compiler.libcxx=libc++ .
- mkdir build
- cd build
- CXXFLAGS="-stdlib=libc++" cmake ..
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T allocator-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -u teletajp:$BINTRAY_API_KEY "https://api.bintray.com/content/teletajp/otus-cpp/homework/$TRAVIS_BUILD_NUMBER/allocator-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"
  
